//! OpenType Layout **language system tags** — the registered
//! vocabulary from the staged registry
//! (`docs/text/opentype/registries/language-tags.html`,
//! OpenType 1.9.1).
//!
//! A language system is "a set of typographic conventions for how
//! text in a given script should be presented" — tags do **not**
//! correspond one-to-one with languages: one set of conventions may
//! serve several languages, one language may have several convention
//! sets, and registration is perceived-need-based. Where a
//! correlation with languages exists, the registry documents it via
//! ISO 639 identifiers (individual languages from Set 3 or
//! collections from Set 2), which [`language_tags_for_iso639`]
//! searches.
//!
//! Registered tags are three or four capital letters (with a few
//! digit-suffixed exceptions such as `HAI0`/`PLG0`), space-padded to
//! four bytes. The tags `dflt` and `DFLT` are **permanently
//! reserved** as language system tags and must never appear in a
//! font's LangSysRecords: default data lives in each Script table's
//! default LangSys slot, which involves no tag at all.

/// Every registered language system tag:
/// `(registry name, tag, corresponding ISO 639 IDs / information)`,
/// in the registry's order. The third field is the registry's
/// annotation verbatim — usually a comma-separated ISO 639 ID list,
/// occasionally empty or free-form (e.g. the `UPPH` BCP 47 note).
pub const REGISTERED_LANGUAGE_TAGS: &[(&str, [u8; 4], &str)] = &[
    ("Eastern Abenaki", *b"AAQ ", "aaq"),
    ("Abaza", *b"ABA ", "abq"),
    ("Abkhazian", *b"ABK ", "abk"),
    ("Acholi", *b"ACH ", "ach"),
    ("Achi", *b"ACR ", "acr"),
    ("Cypriot Arabic", *b"ACY ", "acy"),
    ("Adyghe", *b"ADY ", "ady"),
    ("Afrikaans", *b"AFK ", "afr"),
    ("Afar", *b"AFR ", "aar"),
    ("Agaw", *b"AGW ", "ahg"),
    ("Aiton", *b"AIO ", "aio"),
    ("Akan", *b"AKA ", "aka, fat, twi"),
    ("Batak Angkola", *b"AKB ", "akb"),
    ("Alsatian", *b"ALS ", "gsw"),
    ("Altai", *b"ALT ", "atv, alt"),
    ("Amharic", *b"AMH ", "amh"),
    ("Anglo-Saxon", *b"ANG ", "ang"),
    ("Arabic", *b"ARA ", "ara"),
    ("Aragonese", *b"ARG ", "arg"),
    ("Aari", *b"ARI ", "aiw"),
    ("Rakhine", *b"ARK ", "mhv, rmz, rki"),
    ("Assamese", *b"ASM ", "asm"),
    ("Asturian", *b"AST ", "ast"),
    ("Athapaskan languages", *b"ATH ", "aht, apa, apk, apj, apl, apm, apw, ath, bea, sek, bcr, caf, chp, clc, coq, crx, ctc, den, dgr, gce, gwi, haa, hoi, hup, ing, kkz, koy, ktw, kuu, mvb, nav, qwt, scs, srs, taa, tau, tcb, tce, tfn, tgx, tht, tol, ttm, tuu, txc, wlk, xup, xsl"),
    ("Gros Ventre (Atsina)", *b"ATS ", "ats"),
    ("Avatime", *b"AVN ", "avn"),
    ("Avar", *b"AVR ", "ava"),
    ("Awadhi", *b"AWA ", "awa"),
    ("Aymara", *b"AYM ", "aym"),
    ("Torki", *b"AZB ", "azb"),
    ("Azerbaijani", *b"AZE ", "aze"),
    ("Badaga", *b"BAD ", "bfq"),
    ("Baghelkhandi", *b"BAG ", "bfy"),
    ("Balkar", *b"BAL ", "krc"),
    ("Balinese", *b"BAN ", "ban"),
    ("Bavarian", *b"BAR ", "bar"),
    ("Baulé", *b"BAU ", "bci"),
    ("Batak Toba", *b"BBC ", "bbc"),
    ("Berber", *b"BBR ", "auj, ber, cnu, gha, gho, grr, jbe, jbn, kab, mzb, oua, rif, sds, shi, shy, siz, sjs, swn, taq, tez, thv, thz, tia, tjo, tmh, ttq, tzm, zen, zgh"),
    ("Bench", *b"BCH ", "bcq"),
    ("Bible Cree", *b"BCR ", ""),
    ("Emberá-Baudó", *b"BDC ", "bdc"),
    ("Bandjalang", *b"BDY ", "bdy"),
    ("Belarusian", *b"BEL ", "bel"),
    ("Bemba", *b"BEM ", "bem"),
    ("Bangla", *b"BEN ", "ben"),
    ("Haryanvi", *b"BGC ", "bgc"),
    ("Bagri", *b"BGQ ", "bgq"),
    ("Bulgarian", *b"BGR ", "bul"),
    ("Bhili", *b"BHI ", "bhi, bhb"),
    ("Bhojpuri", *b"BHO ", "bho"),
    ("Bikol", *b"BIK ", "bik, bhk, bcl, bto, cts, bln, fbl, lbl, rbl, ubl"),
    ("Bilen", *b"BIL ", "byn"),
    ("Bislama", *b"BIS ", "bis"),
    ("Kanauji", *b"BJJ ", "bjj"),
    ("Blackfoot", *b"BKF ", "bla"),
    ("Baluchi", *b"BLI ", "bal"),
    ("Pa’o Karen", *b"BLK ", "blk"),
    ("Balante", *b"BLN ", "bjt, ble"),
    ("Balti", *b"BLT ", "bft"),
    ("Bambara (Bamanankan)", *b"BMB ", "bam"),
    ("Bamileke", *b"BML ", "bai, bbj, bko, byv, fmp, jgo, nla, nnh, nnz, nwe, xmg, ybb"),
    ("Bosnian", *b"BOS ", "bos"),
    ("Bishnupriya Manipuri", *b"BPY ", "bpy"),
    ("Breton", *b"BRE ", "bre"),
    ("Brahui", *b"BRH ", "brh"),
    ("Braj Bhasha", *b"BRI ", "bra"),
    ("Burmese", *b"BRM ", "mya"),
    ("Bodo", *b"BRX ", "brx"),
    ("Bashkir", *b"BSH ", "bak"),
    ("Burushaski", *b"BSK ", "bsk"),
    ("Batak Dairi (Pakpak)", *b"BTD ", "btd"),
    ("Beti", *b"BTI ", "btb, beb, bum, bxp, eto, ewo, mct"),
    ("Batak languages", *b"BTK ", "akb, bbc, btd, btk, btm, bts, btx, btz"),
    ("Batak Mandailing", *b"BTM ", "btm"),
    ("Batak Simalungun", *b"BTS ", "bts"),
    ("Batak Karo", *b"BTX ", "btx"),
    ("Batak Alas-Kluet", *b"BTZ ", "btz"),
    ("Bugis", *b"BUG ", "bug"),
    ("Medumba", *b"BYV ", "byv"),
    ("Kaqchikel", *b"CAK ", "cak"),
    ("Catalan", *b"CAT ", "cat"),
    ("Cayuga", *b"CAY ", "cay"),
    ("Chimila", *b"CBG ", "cbg"),
    ("Zamboanga Chavacano", *b"CBK ", "cbk"),
    ("Cebuano", *b"CEB ", "ceb"),
    ("Chiga", *b"CGG ", "cgg"),
    ("Chamorro", *b"CHA ", "cha"),
    ("Chechen", *b"CHE ", "che"),
    ("Chaha Gurage", *b"CHG ", "sgw"),
    ("Chattisgarhi", *b"CHH ", "hne"),
    ("Chichewa (Chewa, Nyanja)", *b"CHI ", "nya"),
    ("Chukchi", *b"CHK ", "ckt"),
    ("Choctaw", *b"CHO ", "cho"),
    ("Chipewyan", *b"CHP ", "chp"),
    ("Cherokee", *b"CHR ", "chr"),
    ("Chuvash", *b"CHU ", "chv"),
    ("Cheyenne", *b"CHY ", "chy"),
    ("Western Cham", *b"CJA ", "cja"),
    ("Eastern Cham", *b"CJM ", "cjm"),
    ("Emberá-Chamí", *b"CMI ", "cmi"),
    ("Comorian", *b"CMR ", "swb, wlc, wni, zdj"),
    ("Comox", *b"COO ", "coo"),
    ("Coptic", *b"COP ", "cop"),
    ("Cornish", *b"COR ", "cor"),
    ("Corsican", *b"COS ", "cos"),
    ("Creoles", *b"CPP ", "abs, acf, afs, aig, aoa, bah, bew, bis, bjs, bpl, bpq, brc, bxo, bzj, bzk, cbk, ccl, ccm, chn, cks, cpe, cpf, cpi, cpp, cri, crp, crs, dcr, dep, djk, fab, fng, fpe, gac, gcf, gcl, gcr, gib, goq, gpe, gul, gyn, hat, hca, hmo, hwc, icr, idb, ihb, jam, jvd, kcn, kea, kmv, kri, kww, lir, lou, lrt, max, mbf, mcm, mfe, mfp, mkn, mod, msi, mud, mzs, nag, nef, ngm, njt, onx, oor, pap, pcm, pea, pey, pga, pih, pis, pln, pml, pmy, pov, pre, rcf, rop, scf, sci, skw, srm, srn, sta, svc, tas, tch, tcs, tgh, tmg, tpi, trf, tvy, uln, vic, vkp, wes, xmm, ycr"),
    ("Cree", *b"CRE ", "cre"),
    ("Carrier", *b"CRR ", "crx, caf"),
    ("Crimean Tatar", *b"CRT ", "crh"),
    ("Kashubian", *b"CSB ", "csb"),
    ("Church Slavonic", *b"CSL ", "chu"),
    ("Czech", *b"CSY ", "ces"),
    ("Chittagonian", *b"CTG ", "ctg"),
    ("Emberá-Catío", *b"CTO ", "cto"),
    ("Wayanad Chetti", *b"CTT ", "ctt"),
    ("San Blas Kuna", *b"CUK ", "cuk"),
    ("Dagbani", *b"DAG ", "dag"),
    ("Danish", *b"DAN ", "dan"),
    ("Dargwa", *b"DAR ", "dar"),
    ("Dayi", *b"DAX ", "dax"),
    ("Woods Cree", *b"DCR ", "cwd"),
    ("German", *b"DEU ", "deu"),
    ("Dogri (individual language)", *b"DGO ", "dgo"),
    ("Dogri (macrolanguage)", *b"DGR ", "doi"),
    ("Dhangu", *b"DHG ", "dhg"),
    ("Dimli", *b"DIQ ", "diq"),
    ("Divehi (Dhivehi, Maldivian)", *b"DIV ", "div"),
    ("Zarma", *b"DJR ", "dje"),
    ("Dangme", *b"DNG ", "ada"),
    ("Dan", *b"DNJ ", "dnj"),
    ("Dinka", *b"DNK ", "din"),
    ("Dari", *b"DRI ", "prs"),
    ("Dhuwal", *b"DUJ ", "duj, dwu, dwy"),
    ("Dungan", *b"DUN ", "dng"),
    ("Dzongkha", *b"DZN ", "dzo"),
    ("Ebira", *b"EBI ", "igb"),
    ("Eastern Cree", *b"ECR ", "crj, crl"),
    ("Edo", *b"EDO ", "bin"),
    ("Efik", *b"EFI ", "efi"),
    ("Greek", *b"ELL ", "ell"),
    ("Eastern Maninkakan", *b"EMK ", "emk"),
    ("Northern Emberá", *b"EMP ", "emp"),
    ("English", *b"ENG ", "eng"),
    ("Erzya", *b"ERZ ", "myv"),
    ("Spanish", *b"ESP ", "spa"),
    ("Central Yupik", *b"ESU ", "esu"),
    ("Estonian", *b"ETI ", "est"),
    ("Basque", *b"EUQ ", "eus"),
    ("Evenki", *b"EVK ", "evn"),
    ("Even", *b"EVN ", "eve"),
    ("Ewe", *b"EWE ", "ewe"),
    ("French Antillean", *b"FAN ", "acf"),
    ("Persian", *b"FAR ", "fas"),
    ("Fanti", *b"FAT ", "fat"),
    ("Finnish", *b"FIN ", "fin"),
    ("Fijian", *b"FJI ", "fij"),
    ("Dutch (Flemish)", *b"FLE ", "vls"),
    ("Fe’fe’", *b"FMP ", "fmp"),
    ("Forest Enets", *b"FNE ", "enf"),
    ("Fon", *b"FON ", "fon"),
    ("Faroese", *b"FOS ", "fao"),
    ("French", *b"FRA ", "fra"),
    ("Cajun French", *b"FRC ", "frc"),
    ("Frisian", *b"FRI ", "fry"),
    ("Friulian", *b"FRL ", "fur"),
    ("Arpitan", *b"FRP ", "frp"),
    ("Futa", *b"FTA ", "fuf"),
    ("Fulah", *b"FUL ", "ful"),
    ("Nigerian Fulfulde", *b"FUV ", "fuv"),
    ("Ga", *b"GAD ", "gaa"),
    ("Scottish Gaelic", *b"GAE ", "gla"),
    ("Gagauz", *b"GAG ", "gag"),
    ("Galician", *b"GAL ", "glg"),
    ("Garshuni", *b"GAR ", ""),
    ("Garhwali", *b"GAW ", "gbm"),
    ("Geez", *b"GEZ ", "gez"),
    ("Githabul", *b"GIH ", "gih"),
    ("Gilyak", *b"GIL ", "niv"),
    ("Kpelle (Guinea)", *b"GKP ", "gkp"),
    ("Gilaki", *b"GLK ", "glk"),
    ("Gumuz", *b"GMZ ", "guk"),
    ("Gumatj", *b"GNN ", "gnn"),
    ("Gogo", *b"GOG ", "gog"),
    ("Gondi", *b"GON ", "gon"),
    ("Greenlandic", *b"GRN ", "kal"),
    ("Garo", *b"GRO ", "grt"),
    ("Guarani", *b"GUA ", "grn"),
    ("Wayuu", *b"GUC ", "guc"),
    ("Gupapuyngu", *b"GUF ", "guf"),
    ("Gujarati", *b"GUJ ", "guj"),
    ("Gusii", *b"GUZ ", "guz"),
    ("Haitian (Haitian Creole)", *b"HAI ", "hat"),
    ("Haida", *b"HAI0", "hai, hax, hdn"),
    ("Halam (Falam Chin)", *b"HAL ", "cfm"),
    ("Harauti", *b"HAR ", "hoj"),
    ("Hausa", *b"HAU ", "hau"),
    ("Hawaiian", *b"HAW ", "haw"),
    ("Haya", *b"HAY ", "hay"),
    ("Hazaragi", *b"HAZ ", "haz"),
    ("Hammer-Banna", *b"HBN ", "amf"),
    ("Heiltsuk", *b"HEI ", "hei"),
    ("Herero", *b"HER ", "her"),
    ("Hiligaynon", *b"HIL ", "hil"),
    ("Hindi", *b"HIN ", "hin"),
    ("High Mari", *b"HMA ", "mrj"),
    ("A-Hmao", *b"HMD ", "hmd"),
    ("Hmong", *b"HMN ", "hmn"),
    ("Hiri Motu", *b"HMO ", "hmo"),
    ("Hmong Shuat", *b"HMZ ", "hmz"),
    ("Hindko", *b"HND ", "hno, hnd"),
    ("Ho", *b"HO  ", "hoc"),
    ("Harari", *b"HRI ", "har"),
    ("Croatian", *b"HRV ", "hrv"),
    ("Hungarian", *b"HUN ", "hun"),
    ("Halkomelem", *b"HUR ", "hur"),
    ("Armenian", *b"HYE ", "hye, hyw"),
    ("Iban", *b"IBA ", "iba"),
    ("Ibibio", *b"IBB ", "ibb"),
    ("Igbo", *b"IBO ", "ibo"),
    ("Ido", *b"IDO ", "ido"),
    ("Ijo languages", *b"IJO ", "iby, ijc, ije, ijn, ijo, ijs, nkx, okd, okr, orr"),
    ("Interlingue", *b"ILE ", "ile"),
    ("Ilokano", *b"ILO ", "ilo"),
    ("Interlingua", *b"INA ", "ina"),
    ("Indonesian", *b"IND ", "ind"),
    ("Ingush", *b"ING ", "inh"),
    ("Inuktitut", *b"INU ", "iku"),
    ("Nunavik Inuktitut", *b"INUK", "ike, iku"),
    ("Inupiat", *b"IPK ", "ipk"),
    ("Irish", *b"IRI ", "gle"),
    ("Irish Traditional", *b"IRT ", "ghc, gle"),
    ("Irula", *b"IRU ", "iru"),
    ("Icelandic", *b"ISL ", "isl"),
    ("Inari Sami", *b"ISM ", "smn"),
    ("Italian", *b"ITA ", "ita"),
    ("Hebrew", *b"IWR ", "heb"),
    ("Jamaican Creole", *b"JAM ", "jam"),
    ("Japanese", *b"JAN ", "jpn"),
    ("Javanese", *b"JAV ", "jav"),
    ("Lojban", *b"JBO ", "jbo"),
    ("Krymchak", *b"JCT ", "jct"),
    ("Judeo-Tat", *b"JDT ", "jdt"),
    ("Yiddish", *b"JII ", "yid"),
    ("Ladino", *b"JUD ", "lad"),
    ("Jula", *b"JUL ", "dyu"),
    ("Kabardian", *b"KAB ", "kbd"),
    ("Kachchi", *b"KAC ", "kfr"),
    ("Kalenjin", *b"KAL ", "kln"),
    ("Kannada", *b"KAN ", "kan"),
    ("Karachay", *b"KAR ", "krc"),
    ("Georgian", *b"KAT ", "kat"),
    ("Kawi (Old Javanese)", *b"KAW ", "kaw"),
    ("Kazakh", *b"KAZ ", "kaz"),
    ("Kadiwéu", *b"KBC ", "kbc"),
    ("Makonde", *b"KDE ", "kde"),
    ("Kabuverdianu (Crioulo)", *b"KEA ", "kea"),
    ("Kebena", *b"KEB ", "ktb"),
    ("Kekchi", *b"KEK ", "kek"),
    ("Khutsuri Georgian", *b"KGE ", "kat"),
    ("Kube", *b"KGF ", "kgf"),
    ("Khakass", *b"KHA ", "kjh"),
    ("Khanty-Kazim", *b"KHK ", "kca"),
    ("Khmer", *b"KHM ", "khm"),
    ("Khanty-Shurishkar", *b"KHS ", "kca"),
    ("Khamti Shan", *b"KHT ", "kht"),
    ("Khanty-Vakhi", *b"KHV ", "kca"),
    ("Khowar", *b"KHW ", "khw"),
    ("Kikuyu (Gikuyu)", *b"KIK ", "kik"),
    ("Kirghiz (Kyrgyz)", *b"KIR ", "kir"),
    ("Kisii", *b"KIS ", "kqs, kss"),
    ("Kirmanjki", *b"KIU ", "kiu"),
    ("Southern Kiwai", *b"KJD ", "kjd"),
    ("Khinalug", *b"KJJ ", "kjj"),
    ("Eastern Pwo Karen", *b"KJP ", "kjp"),
    ("Bumthangkha", *b"KJZ ", "kjz"),
    ("Kokni", *b"KKN ", "kex"),
    ("Kalmyk", *b"KLM ", "xal"),
    ("Kamba", *b"KMB ", "kam"),
    ("Kâte", *b"KMG ", "kmg"),
    ("Kumaoni", *b"KMN ", "kfy"),
    ("Komo", *b"KMO ", "kmw"),
    ("Komso", *b"KMS ", "kxc"),
    ("Khorasani Turkic", *b"KMZ ", "kmz"),
    ("Kanuri", *b"KNR ", "kau"),
    ("Kodagu", *b"KOD ", "kfa"),
    ("Korean Old Hangul", *b"KOH ", "kor, okm"),
    ("Konkani", *b"KOK ", "kok"),
    ("Komi", *b"KOM ", "kom"),
    ("Kikongo", *b"KON ", "ktu"),
    ("Komi-Permyak", *b"KOP ", "koi"),
    ("Korean", *b"KOR ", "kor"),
    ("Kosraean", *b"KOS ", "kos"),
    ("Komi-Zyrian", *b"KOZ ", "kpv"),
    ("Kpelle", *b"KPL ", "kpe"),
    ("Krio", *b"KRI ", "kri"),
    ("Karakalpak", *b"KRK ", "kaa"),
    ("Karelian", *b"KRL ", "krl"),
    ("Karaim", *b"KRM ", "kdr"),
    ("Karen", *b"KRN ", "blk, bwe, eky, ghk, jkm, jkp, kar, kjp, kjt, ksw, kvl, kvq, kvt, kvu, kvy, kxf, kxk, kyu, pdu, pwo, pww, wea"),
    ("Koorete", *b"KRT ", "kqy"),
    ("Kashmiri", *b"KSH ", "kas"),
    ("Khasi", *b"KSI ", "kha"),
    ("Kildin Sami", *b"KSM ", "sjd"),
    ("Khamyang", *b"KSU ", "ksu"),
    ("S’gaw Karen", *b"KSW ", "ksw"),
    ("Kuanyama", *b"KUA ", "kua"),
    ("Kui", *b"KUI ", "kxu"),
    ("Kulvi", *b"KUL ", "kfx"),
    ("Kumyk", *b"KUM ", "kum"),
    ("Kurdish", *b"KUR ", "kur"),
    ("Kurukh", *b"KUU ", "kru"),
    ("Kuy", *b"KUY ", "kdt"),
    ("Geba Karen", *b"KVQ ", "kvq"),
    ("Kwakʼwala", *b"KWK ", "kwk"),
    ("Koryak", *b"KYK ", "kpy"),
    ("Western Kayah", *b"KYU ", "kyu"),
    ("Ladin", *b"LAD ", "lld"),
    ("Lahuli", *b"LAH ", "bfu"),
    ("Lak", *b"LAK ", "lbe"),
    ("Lambani", *b"LAM ", "lmn"),
    ("Lao", *b"LAO ", "lao"),
    ("Latin", *b"LAT ", "lat"),
    ("Laz", *b"LAZ ", "lzz"),
    ("L-Cree", *b"LCR ", "crm"),
    ("Ladakhi", *b"LDK ", "lbj"),
    ("Lelemi", *b"LEF ", "lef"),
    ("Lezgi", *b"LEZ ", "lez"),
    ("Ligurian", *b"LIJ ", "lij"),
    ("Limburgish", *b"LIM ", "lim"),
    ("Lingala", *b"LIN ", "lin"),
    ("Lisu", *b"LIS ", "lis"),
    ("Liv", *b"LIV ", "liv"),
    ("Lampung", *b"LJP ", "ljp"),
    ("Laki", *b"LKI ", "lki"),
    ("Low Mari", *b"LMA ", "mhr"),
    ("Limbu", *b"LMB ", "lif"),
    ("Lombard", *b"LMO ", "lmo"),
    ("Lomwe", *b"LMW ", "ngl"),
    ("Loma", *b"LOM ", "lom"),
    ("Lipo", *b"LPO ", "lpo"),
    ("Luri", *b"LRC ", "lrc, luz, bqi, zum"),
    ("Lower Sorbian", *b"LSB ", "dsb"),
    ("Lule Sami", *b"LSM ", "smj"),
    ("Lithuanian", *b"LTH ", "lit"),
    ("Luxembourgish", *b"LTZ ", "ltz"),
    ("Luba-Lulua", *b"LUA ", "lua"),
    ("Luba-Katanga", *b"LUB ", "lub"),
    ("Ganda", *b"LUG ", "lug"),
    ("Luyia", *b"LUH ", "luy"),
    ("Luo", *b"LUO ", "luo"),
    ("Lushootseed", *b"LUT ", "lut"),
    ("Latvian", *b"LVI ", "lav"),
    ("Madura", *b"MAD ", "mad"),
    ("Magahi", *b"MAG ", "mag"),
    ("Marshallese", *b"MAH ", "mah"),
    ("Majang", *b"MAJ ", "mpe"),
    ("Makhuwa", *b"MAK ", "vmw"),
    ("Malayalam", *b"MAL ", "mal"),
    ("Mam", *b"MAM ", "mam"),
    ("Mansi", *b"MAN ", "mns"),
    ("Mapudungun", *b"MAP ", "arn"),
    ("Marathi", *b"MAR ", "mar"),
    ("Marwari", *b"MAW ", "mwr, dhd, rwr, mve, wry, mtr, swv"),
    ("Mbundu", *b"MBN ", "kmb"),
    ("Mbo", *b"MBO ", "mbo"),
    ("Manchu", *b"MCH ", "mnc"),
    ("Moose Cree", *b"MCR ", "crm"),
    ("Mende", *b"MDE ", "men"),
    ("Mandar", *b"MDR ", "mdr"),
    ("Me’en", *b"MEN ", "mym"),
    ("Meru", *b"MER ", "mer"),
    ("Mano", *b"MEV ", "mev"),
    ("Pattani Malay", *b"MFA ", "mfa"),
    ("Morisyen", *b"MFE ", "mfe"),
    ("Minangkabau", *b"MIN ", "min"),
    ("Mizo", *b"MIZ ", "lus"),
    ("Macedonian", *b"MKD ", "mkd"),
    ("Makasar", *b"MKR ", "mak"),
    ("Kituba", *b"MKW ", "mkw"),
    ("Male", *b"MLE ", "mdy"),
    ("Malagasy", *b"MLG ", "mlg"),
    ("Malinke", *b"MLN ", "mlq"),
    ("Malayalam Reformed", *b"MLR ", "mal"),
    ("Malay", *b"MLY ", "msa"),
    ("Mandinka", *b"MND ", "mnk"),
    ("Mongolian", *b"MNG ", "mon"),
    ("Manipuri", *b"MNI ", "mni"),
    ("Maninka", *b"MNK ", "man, mnk, myq, mku, msc, emk, mwk, mlq"),
    ("Manx", *b"MNX ", "glv"),
    ("Mohawk", *b"MOH ", "moh"),
    ("Moksha", *b"MOK ", "mdf"),
    ("Moldavian", *b"MOL ", "mol"),
    ("Mon", *b"MON ", "mnw"),
    ("Thailand Mon", *b"MONT", "mnw"),
    ("Moroccan", *b"MOR ", ""),
    ("Mossi", *b"MOS ", "mos"),
    ("Maori", *b"MRI ", "mri"),
    ("Maithili", *b"MTH ", "mai"),
    ("Maltese", *b"MTS ", "mlt"),
    ("Mundari", *b"MUN ", "unr"),
    ("Muscogee", *b"MUS ", "mus"),
    ("Mirandese", *b"MWL ", "mwl"),
    ("Hmong Daw", *b"MWW ", "mww"),
    ("Mayan", *b"MYN ", "acr, agu, caa, cac, cak, chf, ckz, cob, ctu, emy, hus, itz, ixl, jac, kek, kjb, knj, lac, mam, mhc, mop, myn, poc, poh, quc, qum, quv, toj, ttc, tzh, tzj, tzo, usp, yua"),
    ("Mazanderani", *b"MZN ", "mzn"),
    ("Naga-Assamese", *b"NAG ", "nag"),
    ("Nahuatl", *b"NAH ", "azd, azn, azz, nah, naz, nch, nci, ncj, ncl, ncx, ngu, nhc, nhe, nhg, nhi, nhk, nhm, nhn, nhp, nhq, nht, nhv, nhw, nhx, nhy, nhz, nlv, npl, nsu, nuz"),
    ("Nanai", *b"NAN ", "gld"),
    ("Neapolitan", *b"NAP ", "nap"),
    ("Naskapi", *b"NAS ", "nsk"),
    ("Nauruan", *b"NAU ", "nau"),
    ("Navajo", *b"NAV ", "nav"),
    ("N-Cree", *b"NCR ", "csw"),
    ("Ndebele", *b"NDB ", "nbl, nde"),
    ("Ndau", *b"NDC ", "ndc"),
    ("Ndonga", *b"NDG ", "ndo"),
    ("Low Saxon", *b"NDS ", "nds"),
    ("Nepali", *b"NEP ", "nep"),
    ("Newari", *b"NEW ", "new"),
    ("Ngbaka", *b"NGA ", "nga"),
    ("Nagari", *b"NGR ", ""),
    ("Norway House Cree", *b"NHC ", "csw"),
    ("Nisi", *b"NIS ", "dap, njz, tgj"),
    ("Niuean", *b"NIU ", "niu"),
    ("Nyankole", *b"NKL ", "nyn"),
    ("N’Ko", *b"NKO ", "nqo"),
    ("Dutch", *b"NLD ", "nld"),
    ("Nimadi", *b"NOE ", "noe"),
    ("Nogai", *b"NOG ", "nog"),
    ("Numanggang", *b"NOP ", "nop"),
    ("Norwegian", *b"NOR ", "nob"),
    ("Novial", *b"NOV ", "nov"),
    ("Northern Sami", *b"NSM ", "sme"),
    ("Northern Sotho", *b"NSO ", "nso"),
    ("Northern Tai", *b"NTA ", "nod"),
    ("Esperanto", *b"NTO ", "epo"),
    ("Nuu-chah-nulth", *b"NUK ", "nuk"),
    ("Nyamwezi", *b"NYM ", "nym"),
    ("Norwegian Nynorsk (Nynorsk, Norwegian)", *b"NYN ", "nno"),
    ("Mbembe Tigon", *b"NZA ", "nza"),
    ("Occitan", *b"OCI ", "oci"),
    ("Oji-Cree", *b"OCR ", "ojs"),
    ("Ojibway", *b"OJB ", "oji"),
    ("Oneida", *b"ONE ", "one"),
    ("Onondaga", *b"ONO ", "ono"),
    ("Odia", *b"ORI ", "ori"),
    ("Oromo", *b"ORO ", "orm"),
    ("Ossetian", *b"OSS ", "oss"),
    ("Palestinian Aramaic", *b"PAA ", "sam"),
    ("Pangasinan", *b"PAG ", "pag"),
    ("Pali", *b"PAL ", "pli"),
    ("Pampangan", *b"PAM ", "pam"),
    ("Punjabi", *b"PAN ", "pan"),
    ("Palpa", *b"PAP ", "plp"),
    ("Pashto", *b"PAS ", "pus"),
    ("Palauan", *b"PAU ", "pau"),
    ("Bouyei", *b"PCC ", "pcc"),
    ("Picard", *b"PCD ", "pcd"),
    ("Pennsylvania German", *b"PDC ", "pdc"),
    ("Polytonic Greek", *b"PGR ", "ell"),
    ("Phake", *b"PHK ", "phk"),
    ("Norfolk", *b"PIH ", "pih"),
    ("Filipino", *b"PIL ", "fil"),
    ("Palaung", *b"PLG ", "pce, rbb, pll"),
    ("Pilagá", *b"PLG0", "plg"),
    ("Polish", *b"PLK ", "pol"),
    ("Piemontese", *b"PMS ", "pms"),
    ("Western Panjabi", *b"PNB ", "pnb"),
    ("Pocomchi", *b"POH ", "poh"),
    ("Pohnpeian", *b"PON ", "pon"),
    ("Provençal / Old Provençal", *b"PRO ", "pro"),
    ("Portuguese", *b"PTG ", "por"),
    ("Western Pwo Karen", *b"PWO ", "pwo"),
    ("Chin", *b"QIN ", "bgr, biu, cek, cey, cfm, cbl, cka, ckn, clj, clt, cmr, cnb, cnh, cnk, cnw, csh, csj, csv, csy, ctd, cth, czt, dao, gnb, hlt, hmr, hra, lus, mrh, mwq, pck, pkh, pub, ral, rtc, sch, sez, shl, smt, tcp, tcz, vap, weu, zom, zyp"),
    ("K’iche’", *b"QUC ", "quc"),
    ("Quechua (Bolivia)", *b"QUH ", "quh"),
    ("Quechua", *b"QUZ ", "quz"),
    ("Quechua (Ecuador)", *b"QVI ", "qvi"),
    ("Quechua (Peru)", *b"QWH ", "qwh"),
    ("Rajasthani", *b"RAJ ", "raj"),
    ("Rarotongan", *b"RAR ", "rar"),
    ("Russian Buriat", *b"RBU ", "bxr"),
    ("R-Cree", *b"RCR ", "atj"),
    ("Rejang", *b"REJ ", "rej"),
    ("Riang", *b"RIA ", "ria"),
    ("Rohingya", *b"RHG ", "rhg"),
    ("Tarifit", *b"RIF ", "rif"),
    ("Ritarungo", *b"RIT ", "rit"),
    ("Arakwal", *b"RKW ", "rkw"),
    ("Romansh", *b"RMS ", "roh"),
    ("Vlax Romani", *b"RMY ", "rmy"),
    ("Romanian", *b"ROM ", "ron"),
    ("Romany", *b"ROY ", "rom"),
    ("Rusyn", *b"RSY ", "rue"),
    ("Rotuman", *b"RTM ", "rtm"),
    ("Kinyarwanda", *b"RUA ", "kin"),
    ("Rundi", *b"RUN ", "run"),
    ("Aromanian", *b"RUP ", "rup"),
    ("Russian", *b"RUS ", "rus"),
    ("Sadri", *b"SAD ", "sck"),
    ("Sanskrit", *b"SAN ", "san"),
    ("Sasak", *b"SAS ", "sas"),
    ("Santali", *b"SAT ", "sat"),
    ("Sayisi", *b"SAY ", "chp"),
    ("Sicilian", *b"SCN ", "scn"),
    ("Scots", *b"SCO ", "sco"),
    ("North Slavey", *b"SCS ", "scs"),
    ("Seneca", *b"SEE ", "see"),
    ("Sekota", *b"SEK ", "xan"),
    ("Selkup", *b"SEL ", "sel"),
    ("Small Flowery Miao", *b"SFM ", "sfm"),
    ("Old Irish", *b"SGA ", "mga, sga"),
    ("Sango", *b"SGO ", "sag"),
    ("Samogitian", *b"SGS ", "sgs"),
    ("Tachelhit", *b"SHI ", "shi"),
    ("Shan", *b"SHN ", "shn"),
    ("Sibe", *b"SIB ", "sjo"),
    ("Sidamo", *b"SID ", "sid"),
    ("Silte Gurage", *b"SIG ", "xst, stv, wle"),
    ("Epena", *b"SJA ", "sja"),
    ("Pite Sami", *b"SJE ", "sje"),
    ("Ume Sami", *b"SJU ", "sju"),
    ("Skolt Sami", *b"SKS ", "sms"),
    ("Slovak", *b"SKY ", "slk"),
    ("Slavey", *b"SLA ", "den, scs, xsl"),
    ("Slovenian", *b"SLV ", "slv"),
    ("Somali", *b"SML ", "som"),
    ("Samoan", *b"SMO ", "smo"),
    ("Sena", *b"SNA ", "seh"),
    ("Sindhi", *b"SND ", "snd"),
    ("Sinhala (Sinhalese)", *b"SNH ", "sin"),
    ("Soninke", *b"SNK ", "snk"),
    ("Sodo Gurage", *b"SOG ", "gru"),
    ("Songe", *b"SOP ", "sop"),
    ("Southern Sotho", *b"SOT ", "sot"),
    ("Albanian", *b"SQI ", "sqi"),
    ("Serbian", *b"SRB ", "cnr, srp"),
    ("Sardinian", *b"SRD ", "srd"),
    ("Saraiki", *b"SRK ", "skr"),
    ("Serer", *b"SRR ", "srr"),
    ("South Slavey", *b"SSL ", "xsl"),
    ("Southern Sami", *b"SSM ", "sma"),
    ("Straits Salish", *b"STR ", "str"),
    ("Saterland Frisian", *b"STQ ", "stq"),
    ("Sukuma", *b"SUK ", "suk"),
    ("Sundanese", *b"SUN ", "sun"),
    ("Suri", *b"SUR ", "suq"),
    ("Svan", *b"SVA ", "sva"),
    ("Swedish", *b"SVE ", "swe"),
    ("Swadaya Aramaic", *b"SWA ", "aii"),
    ("Swahili", *b"SWK ", "swa"),
    ("Swati", *b"SWZ ", "ssw"),
    ("Sutu", *b"SXT ", "ngo, xnj, xnq"),
    ("Upper Saxon", *b"SXU ", "sxu"),
    ("Sylheti", *b"SYL ", "syl"),
    ("Syriac", *b"SYR ", "aii, amw, cld, syc, syr, tru"),
    ("Silesian", *b"SZL ", "szl"),
    ("Tabasaran", *b"TAB ", "tab"),
    ("Tajiki", *b"TAJ ", "tgk"),
    ("Tamil", *b"TAM ", "tam"),
    ("Tamasheq", *b"TAQ ", "taq"),
    ("Tatar", *b"TAT ", "tat"),
    ("Tobo", *b"TBV ", "tbv"),
    ("TH-Cree", *b"TCR ", "cwd"),
    ("Emberá-Tadó", *b"TDC ", "tdc"),
    ("Dehong Dai", *b"TDD ", "tdd"),
    ("Telugu", *b"TEL ", "tel"),
    ("Tetum", *b"TET ", "tet"),
    ("Tagalog", *b"TGL ", "tgl"),
    ("Tongan", *b"TGN ", "ton"),
    ("Tigre", *b"TGR ", "tig"),
    ("Tigrinya", *b"TGY ", "tir"),
    ("Thai", *b"THA ", "tha"),
    ("Tahitian", *b"THT ", "tah"),
    ("Thompson", *b"THP ", "thp"),
    ("Tahaggart Tamahaq", *b"THV ", "thv"),
    ("Tayart Tamajeq", *b"THZ ", "thz"),
    ("Tibetan", *b"TIB ", "bod"),
    ("Tiv", *b"TIV ", "tiv"),
    ("Tai Laing", *b"TJL ", "tjl"),
    ("Turkmen", *b"TKM ", "tuk"),
    ("Tlingit", *b"TLI ", "tli"),
    ("Tamashek", *b"TMH ", "taq, thv, thz, tmh, ttq"),
    ("Talysh", *b"TLY ", "tly"),
    ("Temne", *b"TMN ", "tem"),
    ("Tswana", *b"TNA ", "tsn"),
    ("Tundra Enets", *b"TNE ", "enh"),
    ("Tonga", *b"TNG ", "toi"),
    ("Todo", *b"TOD ", "xal"),
    ("Tok Pisin", *b"TPI ", "tpi"),
    ("Turkish", *b"TRK ", "tur"),
    ("Tsonga", *b"TSG ", "tso"),
    ("Tshangla", *b"TSJ ", "tsj"),
    ("Tawallammat Tamajaq", *b"TTQ ", "ttq"),
    ("Turoyo Aramaic", *b"TUA ", "tru"),
    ("Tulu", *b"TUL ", "tcy"),
    ("Tumbuka", *b"TUM ", "tum"),
    ("Tuscarora", *b"TUS ", "tus"),
    ("Tuvin", *b"TUV ", "tyv"),
    ("Tuvalu", *b"TVL ", "tvl"),
    ("Twi", *b"TWI ", "twi"),
    ("Tày", *b"TYZ ", "tyz"),
    ("Tamazight", *b"TZM ", "tzm"),
    ("Tzotzil", *b"TZO ", "tzo"),
    ("Udi", *b"UDI ", "udi"),
    ("Udmurt", *b"UDM ", "udm"),
    ("Ukrainian", *b"UKR ", "ukr"),
    ("Umbundu", *b"UMB ", "umb"),
    ("Uralic Phonetic Alphabet", *b"UPPH", "Cf. BCP 47 variant subtag “fonupa” (see https://www.iana.org/assignments/lang-subtags-templates/fonupa.txt)"),
    ("Urdu", *b"URD ", "urd"),
    ("Upper Sorbian", *b"USB ", "hsb"),
    ("Uyghur", *b"UYG ", "uig"),
    ("Uzbek", *b"UZB ", "uzb"),
    ("Venetian", *b"VEC ", "vec"),
    ("Venda", *b"VEN ", "ven"),
    ("Vietnamese", *b"VIT ", "vie"),
    ("Volapük", *b"VOL ", "vol"),
    ("Võro", *b"VRO ", "vro"),
    ("Wa", *b"WA  ", "wbm"),
    ("Wagdi", *b"WAG ", "wbr"),
    ("Waray-Waray", *b"WAR ", "war"),
    ("Wakhi", *b"WBL ", "wbl"),
    ("Waci Gbe", *b"WCI ", "wci"),
    ("West-Cree", *b"WCR ", "crk"),
    ("Wendat", *b"WDT ", "wdt"),
    ("Welsh", *b"WEL ", "cym"),
    ("Wolof", *b"WLF ", "wol"),
    ("Walloon", *b"WLN ", "wln"),
    ("Mewati", *b"WTM ", "wtm"),
    ("Wyandot", *b"WYN ", "wyn"),
    ("Lü", *b"XBD ", "khb"),
    ("Xhosa", *b"XHS ", "xho"),
    ("Minjangbal", *b"XJB ", "xjb"),
    ("Khengkha", *b"XKF ", "xkf"),
    ("Soga", *b"XOG ", "xog"),
    ("Kpelle (Liberia)", *b"XPE ", "xpe"),
    ("Bette Kuruma", *b"XUB ", "xub"),
    ("Jennu Kuruma", *b"XUJ ", "xuj"),
    ("Sakha", *b"YAK ", "sah"),
    ("Yao", *b"YAO ", "yao"),
    ("Yapese", *b"YAP ", "yap"),
    ("Yoruba", *b"YBA ", "yor"),
    ("Y-Cree", *b"YCR ", "crj, crk, crl"),
    ("Gepo", *b"YGP ", "ygp"),
    ("Yi Classic", *b"YIC ", ""),
    ("Yi Modern", *b"YIM ", "iii"),
    ("Aluo", *b"YNA ", "yna"),
    ("Havasupai-Walapai-Yavapai", *b"YUF ", "yuf"),
    ("Wuding-Luquan Yi", *b"YWQ ", "ywq"),
    ("Zealandic", *b"ZEA ", "zea"),
    ("Standard Moroccan Tamazight", *b"ZGH ", "zgh"),
    ("Zhuang", *b"ZHA ", "zha"),
    ("Chinese, Traditional, Hong Kong SAR", *b"ZHH ", "zho"),
    ("Chinese, Phonetic", *b"ZHP ", "zho"),
    ("Chinese, Simplified", *b"ZHS ", "zho"),
    ("Chinese, Traditional", *b"ZHT ", "zho"),
    ("Chinese, Traditional, Macao SAR", *b"ZHTM", "zho"),
    ("Zande", *b"ZND ", "zne"),
    ("Zulu", *b"ZUL ", "zul"),
    ("Zazaki", *b"ZZA ", "zza"),
];

/// Whether `tag` is a registered language system tag.
pub fn is_registered_language_tag(tag: [u8; 4]) -> bool {
    REGISTERED_LANGUAGE_TAGS.iter().any(|(_, t, _)| *t == tag)
}

/// The registry name for a language system tag (tags are unique in
/// the registry).
pub fn language_tag_name(tag: [u8; 4]) -> Option<&'static str> {
    REGISTERED_LANGUAGE_TAGS
        .iter()
        .find(|(_, t, _)| *t == tag)
        .map(|(n, _, _)| *n)
}

/// Every language system tag whose registry annotation lists the
/// given ISO 639 identifier (case-insensitive exact ID match within
/// the comma-separated list), in registry order. More than one tag
/// may serve a language (e.g. `hai` appears under both `HAI ` and
/// `HAI0`), and a tag may list several IDs.
pub fn language_tags_for_iso639(iso639: &str) -> Vec<[u8; 4]> {
    REGISTERED_LANGUAGE_TAGS
        .iter()
        .filter(|(_, _, ids)| {
            ids.split(',')
                .map(str::trim)
                .any(|id| id.eq_ignore_ascii_case(iso639))
        })
        .map(|(_, t, _)| *t)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_shape_and_lookups() {
        // 661 rows transcribed from the registry; tags are unique.
        assert_eq!(REGISTERED_LANGUAGE_TAGS.len(), 661);
        for w in REGISTERED_LANGUAGE_TAGS.windows(1) {
            let (name, tag, _) = w[0];
            assert!(!name.is_empty());
            // Three or four capitals (or a digit suffix), space-padded.
            assert!(
                tag.iter()
                    .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() || *b == b' '),
                "{name}"
            );
        }
        let tags: Vec<[u8; 4]> = REGISTERED_LANGUAGE_TAGS
            .iter()
            .map(|(_, t, _)| *t)
            .collect();
        let mut dedup = tags.clone();
        dedup.sort_unstable();
        dedup.dedup();
        assert_eq!(dedup.len(), tags.len());

        assert!(is_registered_language_tag(*b"ENG "));
        assert!(is_registered_language_tag(*b"HO  "));
        assert!(is_registered_language_tag(*b"HAI0"));
        // dflt/DFLT are reserved, never registered.
        assert!(!is_registered_language_tag(*b"DFLT"));
        assert!(!is_registered_language_tag(*b"dflt"));

        assert_eq!(language_tag_name(*b"ENG "), Some("English"));
        assert_eq!(language_tag_name(*b"JAN "), Some("Japanese"));
        assert_eq!(language_tag_name(*b"ZHS "), Some("Chinese, Simplified"));
        assert_eq!(language_tag_name(*b"zzzz"), None);
    }

    #[test]
    fn iso639_reverse_lookup() {
        // The registry's Japanese row lists jpn.
        assert_eq!(language_tags_for_iso639("jpn"), vec![*b"JAN "]);
        // hai is listed under both HAI (via collection) and HAI0.
        let hai = language_tags_for_iso639("hai");
        assert!(hai.contains(b"HAI0"), "{hai:?}");
        // Multi-ID row: hax is one of HAI0's IDs.
        assert!(language_tags_for_iso639("hax").contains(b"HAI0"));
        // Case-insensitive; unknown IDs yield nothing.
        assert_eq!(
            language_tags_for_iso639("JPN"),
            language_tags_for_iso639("jpn")
        );
        assert!(language_tags_for_iso639("qqq").is_empty());
        // German: deu listed under DEU.
        assert!(language_tags_for_iso639("deu").contains(b"DEU "));
    }
}
